### ISSUE TITLE
Issue reading 5 digit register instat of 6.

### ISSUE THREAD

**Issue by whoopsie** [tallakt/modbus-cli#10]
I was trying to read a Modbus register **30775**  but it need a 6 digit number so used **030775**. Unit ID is 3 en IP is 10.11.71.11. When i do a ping to 10.11.71.11 i got back that it works. 

What am i doing wrong.
```
[root@localhost svcvdp]# modbus read -s3 10.11.71.11 030775 1
/usr/local/share/gems/gems/rmodbus-1.3.3/lib/rmodbus/slave.rb:241:in `rescue in query': Timed out during read attempt (ModBus::Errors::ModBusTimeout)
	from /usr/local/share/gems/gems/rmodbus-1.3.3/lib/rmodbus/slave.rb:232:in `query'
	from /usr/local/share/gems/gems/rmodbus-1.3.3/lib/rmodbus/slave.rb:46:in `read_coils'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:128:in `block in read_data_coils'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:127:in `each_slice'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:127:in `read_data_coils'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:69:in `read_coils'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:91:in `block (2 levels) in execute'
	from /usr/local/share/gems/gems/rmodbus-1.3.3/lib/rmodbus/client.rb:55:in `with_slave'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:77:in `block in execute'
	from /usr/local/share/gems/gems/rmodbus-1.3.3/lib/rmodbus/client.rb:26:in `initialize'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:76:in `new'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/lib/modbus-cli/read_command.rb:76:in `execute'
	from /usr/local/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
	from /usr/local/share/gems/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
	from /usr/local/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /usr/local/share/gems/gems/modbus-cli-0.0.13/bin/modbus:6:in `<top (required)>'
	from /usr/local/bin/modbus:23:in `load'
	from /usr/local/bin/modbus:23:in `<main>'
```

**Comment by tallakt** [comment]
You should probably try address 300775 or %MW774

Modbus adresses are sometimes specifies +30_000, sometime +300_000. The former normally for serial port (RTU) and the latter for TCP.

modbus_cli will use that convention...

**Comment by whoopsie** [comment]
Okay now i got some data. Only all the register giving the same information back only the registers are not the same. It are U32 or S32 Type data.
```
[root@localhost solar]# modbus read -s 3 10.11.71.11 300513 1
300513      65535
[root@localhost solar]# modbus read -s 3 10.11.71.11 300775 1
300775      65535
[root@localhost solar]# modbus read -s 3 10.11.71.11 300805 1
300805      65535
[root@localhost solar]# modbus read 10.11.71.11 300805 1
300805      65535
```

**Comment by tallakt** [comment]
Perhaps you are reading from the wrong memory area: https://en.wikipedia.org/wiki/Modbus

Try for instance 40000x or 10000x...
